package dev.anthonyhfm.amethyst.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

data class AmethystColorPalette(
    val background: Color,
    val foreground: Color,
    val card: Color,
    val cardForeground: Color,
    val popover: Color,
    val popoverForeground: Color,
    val primary: Color,
    val primaryForeground: Color,
    val secondary: Color,
    val secondaryForeground: Color,
    val muted: Color,
    val mutedForeground: Color,
    val accent: Color,
    val accentForeground: Color,
    val destructive: Color,
    val destructiveForeground: Color,
    val selectionSurface: Color,
    val selectionForeground: Color,
    val selectionBorder: Color,
    val border: Color,
    val input: Color,
    val ring: Color,
    val chart1: Color,
    val chart2: Color,
    val chart3: Color,
    val chart4: Color,
    val chart5: Color,
)

val AmethystLightPalette = AmethystColorPalette(
    background = Color(0xFFFFFFFF),
    foreground = Color(0xFF030712),
    card = Color(0xFFFFFFFF),
    cardForeground = Color(0xFF030712),
    popover = Color(0xFFFFFFFF),
    popoverForeground = Color(0xFF030712),
    primary = Color(0xFF7C3AED),
    primaryForeground = Color(0xFFF9FAFB),
    secondary = Color(0xFFF3F4F6),
    secondaryForeground = Color(0xFF111827),
    muted = Color(0xFFF3F4F6),
    mutedForeground = Color(0xFF6B7280),
    accent = Color(0xFFF3F4F6),
    accentForeground = Color(0xFF111827),
    destructive = Color(0xFFEF4444),
    destructiveForeground = Color(0xFFF9FAFB),
    selectionSurface = Color(0xFF2563EB),
    selectionForeground = Color(0xFFF8FAFC),
    selectionBorder = Color(0xFF1D4ED8),
    border = Color(0xFFE5E7EB),
    input = Color(0xFFE5E7EB),
    ring = Color(0xFF7C3AED),
    chart1 = Color(0xFFE76E50),
    chart2 = Color(0xFF2A9D90),
    chart3 = Color(0xFF274754),
    chart4 = Color(0xFFE8C468),
    chart5 = Color(0xFFF4A362),
)

val AmethystDarkPalette = AmethystColorPalette(
    background = Color(0xFF030712),
    foreground = Color(0xFFF9FAFB),
    card = Color(0xFF030712),
    cardForeground = Color(0xFFF9FAFB),
    popover = Color(0xFF030712),
    popoverForeground = Color(0xFFF9FAFB),
    primary = Color(0xFF6D28D9),
    primaryForeground = Color(0xFFF9FAFB),
    secondary = Color(0xFF1F2937),
    secondaryForeground = Color(0xFFF9FAFB),
    muted = Color(0xFF1F2937),
    mutedForeground = Color(0xFF9CA3AF),
    accent = Color(0xFF1F2937),
    accentForeground = Color(0xFFF9FAFB),
    destructive = Color(0xFF7F1D1D),
    destructiveForeground = Color(0xFFF9FAFB),
    selectionSurface = Color(0xFF60A5FA),
    selectionForeground = Color(0xFF0B1220),
    selectionBorder = Color(0xFF93C5FD),
    border = Color(0xFF1F2937),
    input = Color(0xFF1F2937),
    ring = Color(0xFF6D28D9),
    chart1 = Color(0xFF2662D9),
    chart2 = Color(0xFF2EB88A),
    chart3 = Color(0xFFE88C30),
    chart4 = Color(0xFFAF57DB),
    chart5 = Color(0xFFE23670),
)

fun amethystColorPalette(darkMode: Boolean): AmethystColorPalette {
    return if (darkMode) AmethystDarkPalette else AmethystLightPalette
}

fun amethystMaterialColorScheme(darkMode: Boolean): ColorScheme {
    val palette = amethystColorPalette(darkMode)

    return if (darkMode) {
        darkColorScheme(
            primary = palette.primary,
            onPrimary = palette.primaryForeground,
            primaryContainer = palette.accent,
            onPrimaryContainer = palette.accentForeground,
            inversePrimary = palette.ring,
            secondary = palette.secondary,
            onSecondary = palette.secondaryForeground,
            secondaryContainer = palette.muted,
            onSecondaryContainer = palette.secondaryForeground,
            tertiary = palette.selectionSurface,
            onTertiary = palette.selectionForeground,
            tertiaryContainer = palette.chart2,
            onTertiaryContainer = palette.foreground,
            background = palette.background,
            onBackground = palette.foreground,
            surface = palette.card,
            onSurface = palette.cardForeground,
            surfaceVariant = palette.muted,
            onSurfaceVariant = palette.mutedForeground,
            outline = palette.border,
            outlineVariant = palette.input,
            error = palette.destructive,
            onError = palette.destructiveForeground,
            errorContainer = palette.destructive.copy(alpha = 0.75f),
            onErrorContainer = palette.destructiveForeground,
            inverseSurface = palette.foreground,
            inverseOnSurface = palette.background,
            surfaceTint = palette.primary,
            scrim = Color.Black.copy(alpha = 0.7f),
        )
    } else {
        lightColorScheme(
            primary = palette.primary,
            onPrimary = palette.primaryForeground,
            primaryContainer = palette.accent,
            onPrimaryContainer = palette.accentForeground,
            inversePrimary = palette.ring,
            secondary = palette.secondary,
            onSecondary = palette.secondaryForeground,
            secondaryContainer = palette.muted,
            onSecondaryContainer = palette.secondaryForeground,
            tertiary = palette.selectionSurface,
            onTertiary = palette.selectionForeground,
            tertiaryContainer = palette.chart2,
            onTertiaryContainer = palette.foreground,
            background = palette.background,
            onBackground = palette.foreground,
            surface = palette.card,
            onSurface = palette.cardForeground,
            surfaceVariant = palette.muted,
            onSurfaceVariant = palette.mutedForeground,
            outline = palette.border,
            outlineVariant = palette.input,
            error = palette.destructive,
            onError = palette.destructiveForeground,
            errorContainer = palette.destructive.copy(alpha = 0.15f),
            onErrorContainer = palette.foreground,
            inverseSurface = palette.foreground,
            inverseOnSurface = palette.background,
            surfaceTint = palette.primary,
            scrim = Color.Black.copy(alpha = 0.35f),
        )
    }
}
